/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SSDI.Assignment1;
import SSDI.Assignment1.GamingPCBuilder;
import SSDI.Assignment1.Builder;


public class App {


    public static void main(String[] args) {
        /*  */
    }
}
